# Dependencies
markdown:         Kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Laboratory of Urban Complexity and Sustainability
tagline:          'LUCAS'
description:      'The LUCAS blog about modelling sustainable urban habitats'
url:              https://julianrosser.bitbucket.io
baseurl:          /
#baseurl:          /~ezzjfr/test_blog/_site/

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo
  email:          julian@offspring.net

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

gems: [jekyll-paginate]