# Dependencies
markdown:         Kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Laboratory of Urban Complexity and Sustainability
tagline:          'LUCAS'
description:      'News and updates from the University of Nottingham LUCAS group'
url:              https://lucas-uk.github.io/
baseurl:          /

author:
  name:           'LUCAS blogger'
  url:            https://nottingham.ac.uk/research/groups/lucas/index.aspx
  email:          lucas-info@nottingham.ac.uk

paginate:         5

# Custom vars
version:          2.1.0

github:
 repo:           https://github.com/lucas-uk/

gems:
  - jekyll-paginate
  - jekyll-seo-tag